import Head from 'next/head';

import { Inter } from '@next/font/google';

import type { Movie } from '@/types';

const inter = Inter({ subsets: ['latin'] });
interface HomeProps {
  data: Movie[];
}

export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>MyFlix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
